name: watt_test
description: "Test for watt company, flutter project utilizing google_maps and getx state management with MVC Architecture"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  bot_toast: ^4.1.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.1.0
  get: ^4.6.6
  get_it: ^7.6.7
  get_storage: ^2.1.1
  google_maps_flutter: ^2.5.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
